chain_width = 30
comment_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
use_small_heuristics = "Default"
wrap_comments = true