#! configuration/production.yaml
application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.mailersend.com/v1/"
  sender_email: "info@trial-pxkjn4136xpgz781.mlsender.net"
  authorization_token: "mlsn.e77c69188ad0d9a1510e1b35e9fc9f47561addb5c82ac68bf9611db835e2e1eb"