#! configuration/production.yaml
application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.mailersend.com/v1/"
  sender_email: "info@trial-pxkjn4136xpgz781.mlsender.net"